/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Fernando
 */
public class ABM_Alumnos_Materias extends javax.swing.JFrame {

    //Own Variables
    private int alumno;
    private ConexionAlumnosMaterias cc = new ConexionAlumnosMaterias();
    private ConexionCarreras cca = new ConexionCarreras();
    
    private ArrayList listaCarreras;
    
    public ABM_Alumnos_Materias(int id_alumno) {
        initComponents();
        alumno = id_alumno;
    }

    public void mostrarDatos(){
        
        
    }
    
    public void mostrarNombre(){
        ResultSet rs = cc.buscarNombreAlumno(alumno);
        try {
            label_campoAlumno.setText(rs.getString(2));
        } catch (SQLException ex) {
            Logger.getLogger(ABM_Alumnos_Materias.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void mostrarCarreras(){
        comboBox_carrera.removeAllItems();
        listaCarreras = cca.getListaCarreras();
        Iterator iterador = listaCarreras.iterator();
        while(iterador.hasNext()){
            Carrera carrera = (Carrera) iterador.next();
            comboBox_carrera.addItem(carrera);
        }
        //AutoCompleteDecorator.decorate(comboBox_carrera);
    }
    
    public void mostrarMaterias(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Contador");
        modelo.addColumn("Nombre");
        modelo.addColumn("Semestre");
        modelo.addColumn("Carrera");
        modelo.addColumn("Id");
        
        table_materias.setModel(modelo);
       
        String[] datos = new String[4];
        try{
            ResultSet rs = cc.buscarMaterias(((Carrera)comboBox_carrera.getSelectedItem()).getId(), Integer.parseInt(((String) comboBox_semestre.getSelectedItem()).trim()));
            int i = 1;
            while(rs.next()){
                datos[0] = String.valueOf(i);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(1);
                                
                modelo.addRow(datos);
                i++;
            }
            table_materias.setModel(modelo);
            TableColumnModel tcm = table_materias.getColumnModel();
            tcm.removeColumn(tcm.getColumn(4));
            tcm.removeColumn(tcm.getColumn(3));
            tcm.removeColumn(tcm.getColumn(2));
            
        }catch(SQLException ex){
            System.out.println("Algo falló");
        }
    }
    
    public void mostarMateriasCursadas(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Contador");
        modelo.addColumn("Nombre");
        modelo.addColumn("Semestre");
        modelo.addColumn("Carrera");
        modelo.addColumn("Id");
        
        table_materias.setModel(modelo);
       
        String[] datos = new String[4];
        try{
            ResultSet rs = cc.buscarMaterias(((Carrera)comboBox_carrera.getSelectedItem()).getId(), Integer.parseInt(((String) comboBox_semestre.getSelectedItem()).trim()));
            int i = 1;
            while(rs.next()){
                datos[0] = String.valueOf(i);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(1);
                                
                modelo.addRow(datos);
                i++;
            }
            table_materias.setModel(modelo);
            TableColumnModel tcm = table_materias.getColumnModel();
            tcm.removeColumn(tcm.getColumn(4));
            tcm.removeColumn(tcm.getColumn(3));
            tcm.removeColumn(tcm.getColumn(2));
            
        }catch(SQLException ex){
            System.out.println("Algo falló");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_alumno = new javax.swing.JLabel();
        label_campoAlumno = new javax.swing.JLabel();
        comboBox_carrera = new javax.swing.JComboBox<>();
        label_carrera = new javax.swing.JLabel();
        label_semestre = new javax.swing.JLabel();
        comboBox_semestre = new javax.swing.JComboBox<>();
        button_guardar = new javax.swing.JButton();
        button_cancelar = new javax.swing.JButton();
        label_materias = new javax.swing.JLabel();
        label_materiasCursadas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_materias = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_materiasCursadas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_alumno.setText("Alumno:");

        label_campoAlumno.setText("...");

        comboBox_carrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label_carrera.setText("Carrera:");

        label_semestre.setText("Semestre:");

        comboBox_semestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        button_guardar.setText("Guardar");
        button_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_guardarActionPerformed(evt);
            }
        });

        button_cancelar.setText("Cancelar");

        label_materias.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_materias.setText("Materias");

        label_materiasCursadas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_materiasCursadas.setText("Materias Cursadas");

        table_materias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_materias);

        table_materiasCursadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table_materiasCursadas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(label_semestre)
                                        .addComponent(label_carrera, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label_alumno, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label_campoAlumno)
                                        .addComponent(comboBox_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboBox_semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(83, 83, 83)
                                    .addComponent(label_materias)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label_materiasCursadas)
                                    .addGap(78, 78, 78)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(button_guardar)
                        .addGap(108, 108, 108)
                        .addComponent(button_cancelar)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_alumno)
                    .addComponent(label_campoAlumno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBox_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_carrera))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_semestre)
                    .addComponent(comboBox_semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_materias)
                    .addComponent(label_materiasCursadas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_guardar)
                    .addComponent(button_cancelar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABM_Alumnos_Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABM_Alumnos_Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABM_Alumnos_Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABM_Alumnos_Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABM_Alumnos_Materias(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancelar;
    private javax.swing.JButton button_guardar;
    private javax.swing.JComboBox<Carrera> comboBox_carrera;
    private javax.swing.JComboBox<String> comboBox_semestre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_alumno;
    private javax.swing.JLabel label_campoAlumno;
    private javax.swing.JLabel label_carrera;
    private javax.swing.JLabel label_materias;
    private javax.swing.JLabel label_materiasCursadas;
    private javax.swing.JLabel label_semestre;
    private javax.swing.JTable table_materias;
    private javax.swing.JTable table_materiasCursadas;
    // End of variables declaration//GEN-END:variables
}
